; This file was automatically generated by ScriptHubImporter.py
<<<<<<< Updated upstream
global g_ImportsGameVersion64 := 531
=======
global g_ImportsGameVersion64 := 529
>>>>>>> Stashed changes
global g_ImportsGameVersionPostFix64 := ""